[build]
base = ".site/"
publish = "public"
command = "../netlify.sh"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ./docs ./samples ./tstoy"

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "../netlify.sh"

[context.split1.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "../netlify.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.124.1"

[context.branch-deploy]
command = "../netlify.sh"

[context.branch-deploy.environment]
HUGO_VERSION = "0.124.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
