name: "🐛 Report a documentation issue"
description: >-
  Report an issue with current documentation.
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: >-
        Use this template to report issues with documentation. This can include typos, technical
        and factual errors, grammar, spelling, formatting, presentation, etc.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Existing Issue:** Search the existing issues for this repository. If there is an
            issue that fits your needs do not file a new one. Subscribe, react, or comment on that
            issue instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context.
          required: true
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the problem.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team update
        the documentation. Additional details may not be useful for typos, grammar, formatting, etc.
        For technical or factual errors, please include code snippets and output to show how the
        documentation or implementation is incorrect.
  - type: textarea
    id: suggestion
    validations:
      required: false
    attributes:
      label: Suggested Fix
      description: >-
        If you have an idea for how to fix the problem you're identifying, include it here.
