name: "ðŸ“ Request a new tutorial"
description: >-
  Request a new tutorial for the DSC Samples. If you want to request a new language implementation
  for an existing tutorial, use the "Request a new implementation" template instead.
labels:
  - request-tutorial
  - needs-triage
body:
  - type: markdown
    attributes:
      value: >-
        Use this template to request or suggest a new tutorial for the DSC samples. Tutorials are
        always accompanied by sample code. DSC Resource tutorials have multiple language
        implementations for a shared set of learning goals. You can find more information about
        contributing tutorials in the
        [contributing guide](https://powershell.github.io/DSC-Samples/contributing/tutorials/).

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Existing Issue:** Search the existing issues for this repository. If there is an
            issue that fits your needs do not file a new one. Subscribe, react, or comment on that
            issue instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Tutorial for error handling in a DSC Resource" instead
            of "Handle errors"
          required: true
  - type: dropdown
    id:   kind
    attributes:
      label: Tutorial Kind
      description: >-
        Generic tutorials only have a single implementation. These tutorials are primarily for
        authoring DSC Configuration documents and showing how to use DSC itself. Resource tutorials
        may be implemented in any number of languages. Resource tutorial implementations always
        share the same learning goals and their sample code implements the same specification.
      multiple: false
      options:
        - Generic
        - Resource
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the proposed tutorial. Why is it needed? What gap
        will it fill? Who is the intended user? What scenarios will it address?
      placeholder: |
        Try formulating the need for this tutorial as a user story.

        > As a <role>, I want a tutorial that <synopsis of learning goals>.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team
        understand the proposed tutorial. If you're requesting a resource tutorial and are
        interested in contributing an implementation, please indicate which language you'd like to
        author the implementation in.
