name: "📦 Request a new implementation"
description: >-
  Request a new language implementation for an existing tutorial. If you want to request an
  entirely new tutorial, use the "Request a new tutorial" template instead.
labels:
  - request-implementation
  - needs-triage
body:
  - type: markdown
    attributes:
      value: >-
        Use this template to request a new language implementation for an existing resource
        tutorial. DSC Resource tutorials have multiple language implementations for a shared set of
        learning goals. You can find more information about contributing tutorials in the
        [contributing guide](https://powershell.github.io/DSC-Samples/contributing/tutorials/).
  - type: checkboxes
    id:   prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Existing Issue:** Search the existing issues for this repository. If there is an
            issue that fits your needs do not file a new one. Subscribe, react, or comment on that
            issue instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Tutorial for error handling in a DSC Resource" instead
            of "Handle errors"
          required: true
  - type: dropdown
    id:   tutorial
    attributes:
      label: Tutorial
      description: >-
        Specify the name of the tutorial you're requesting a new language implementation for.
      multiple: false
      options:
        - Write your first DSC Resource
  - type: input
    id:   language
    attributes:
      label: Implementation language
      description: >-
        Specify the programming language you want the new implementation to use. The team has
        experience with C#, Go, and Rust, but you can request the implementation in any language.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team
        with the implementation. If you're willing to contribute the implementation, please
        include that information.
