$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/10/config/document.json
resources:
- name: Desired TimeZone
  type: Microsoft/tzutil
  properties:
    timezone: UTC
    dstoff: false